<?php
    include("../../addons/addons.php");
    include("../../db.php");
    $raAluno = $_POST['raAluno'];
    include("../../addons/buscar_notas_faltas.php");
    echo "
        <tbody>
            <tr>
                <th>Português</th>
                <th>$ntPort1</th>
                <th>$ftPort1</th>
                <th>$ntPort2</th>
                <th>$ftPort2</th>
                <th>$ntPort3</th>
                <th>$ftPort3</th>
                <th>$ntPort4</th>
                <th>$ftPort4</th>
            </tr>
            <tr>
                <th>Matemática</th>
                <th>$ntMat1</th>
                <th>$ftMat1</th>
                <th>$ntMat2</th>
                <th>$ftMat2</th>
                <th>$ntMat3</th>
                <th>$ftMat3</th>
                <th>$ntMat4</th>
                <th>$ftMat4</th>
            </tr>
            <tr>
                <th>Ciências</th>
                <th>$ntCien1</th>
                <th>$ftCien1</th>
                <th>$ntCien2</th>
                <th>$ftCien2</th>
                <th>$ntCien3</th>
                <th>$ftCien3</th>
                <th>$ntCien4</th>
                <th>$ftCien4</th>
            </tr>
            <tr>
                <th>História</th>
                <th>$ntHist1</th>
                <th>$ftHist1</th>
                <th>$ntHist2</th>
                <th>$ftHist2</th>
                <th>$ntHist3</th>
                <th>$ftHist3</th>
                <th>$ntHist4</th>
                <th>$ftHist4</th>
            </tr>
            <tr>
                <th>Geografia</th>
                <th>$ntGeo1</th>
                <th>$ftGeo1</th>
                <th>$ntGeo2</th>
                <th>$ftGeo2</th>
                <th>$ntGeo3</th>
                <th>$ftGeo3</th>
                <th>$ntGeo4</th>
                <th>$ftGeo4</th>
            </tr>
            <tr>
                <th>Artes</th>
                <th>$ntArte1</th>
                <th>$ftArte1</th>
                <th>$ntArte2</th>
                <th>$ftArte2</th>
                <th>$ntArte3</th>
                <th>$ftArte3</th>
                <th>$ntArte4</th>
                <th>$ftArte4</th>
            </tr>
            <tr>
                <th>Ed. Física</th>
                <th>$ntEdFisc1</th>
                <th>$ftEdFisc1</th>
                <th>$ntEdFisc2</th>
                <th>$ftEdFisc2</th>
                <th>$ntEdFisc3</th>
                <th>$ftEdFisc3</th>
                <th>$ntEdFisc4</th>
                <th>$ftEdFisc4</th>
            </tr>
            <tr>
                <th>Inglês</th>
                <th>$ntIngl1</th>
                <th>$ftIngl1</th>
                <th>$ntIngl2</th>
                <th>$ftIngl2</th>
                <th>$ntIngl3</th>
                <th>$ftIngl3</th>
                <th>$ntIngl4</th>
                <th>$ftIngl4</th>
            </tr>
        </tbody>";
?>